/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    Header: typeof import('./resources/js/components/Header.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    NavBar: typeof import('./resources/js/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    WelcomeMessage: typeof import('./resources/js/components/WelcomeMessage.vue')['default']
    WishlistButton: typeof import('./resources/js/components/WishlistButton.vue')['default']
  }
}
